theme: jekyll-theme-minimal

title: "Jamshid Ardalankia"
description: "PhD Candidate in Economics · Financial Networks · Systemic Risk · Quantitative Finance"

logo: /assets/profile.jpg

github_username:  jamshidardalankia
linkedin: "https://www.linkedin.com/feed/"
scholar: "https://scholar.google.com/citations?hl=en&user=0sMvul4AAAAJ"
email: "ardalankia@vt.edu"
